### ISSUE TITLE
Not available repo

### ISSUE THREAD

**Issue by koumaza** [BrianTestShit/android_system_bt#3]
https://github.com/BrianTestShit/android_system_bt/blob/Q/snippets/rr.xml#L26
https://github.com/BrianTestShit/android_system_bt/blob/Q/snippets/rr.xml#L59

Is this repository private or not in use?

**Comment by varund7726** [comment]
Private .this rom is not public for building

**Comment by koumaza** [comment]
Ok thanks

**Comment by varund7726** [comment]
will update when sources go public

**Comment by BlackDeaths** [comment]
When can we expect roughly?
We are longing for it.
Sincerely yours.
